### ISSUE TITLE
Minimal Example Presentation Work

### ISSUE THREAD

**Issue by 464hee** [liupei101/PseMix#1]
Hello, thanks for your work, I think your work is groundbreaking, but I think if more people apply it to their work, it may be necessary for you to present a minimal sample code flow to facilitate a better understanding of your work @liupei101

**Comment by liupei101** [comment]
Thanks for your interest and good suggestions!

We will show a minimal code example to better illustrate our work. I have tagged this issue as `documentation`. It will be finished as soon as possible, maybe in the next few days (based on my schedule). 

Thx again.

**Comment by liupei101** [comment]
close as completed
