### ISSUE TITLE
datasplit for c16

### ISSUE THREAD

**Issue by ptoyip** [liupei101/PseMix#2]
Thanks for the inspiring paper.
I was trying to replicate the result for Camelyon 16 on TransMIL, while I was reading the config, I was confused by the split path (.npz), as I think CLAM datasplit does not generate any .npz file. May I know what file should I use or there exist a workaround?
Thanks in advance.

**Comment by liupei101** [comment]
Thanks for your interest. 

Yes, CLAM does not generate `.npz` files. The `.npz` files should be generated by yourself, if you run on a new dataset beyond those we have included in this repo. A valid `.npz` file could be generated using the following pseudo-code:
```python
import numpy as np

YOUR_SAVE_PATH = './data_split.npz'
pids_new_train = ['train_001', ..., 'train_100'] # each string should correspond to your training slide ID
pids_new_val = ['val_01', ..., 'val_10'] # each string should correspond to your validation slide ID
pids_new_test = ['test_01', ..., 'test_100'] # each string should correspond to your test slide ID
np.savez(
    YOUR_SAVE_PATH,
    train_patients=pids_new_train,
    val_patients=pids_new_val,
    test_patients=pids_test
)
``` 

For Camelyon16, its training and test slide IDs have been provided. So it is easy to prepare the `.npz` file, with a bit of effort putting to randomly split some samples from training samples as the validation data.
