### ISSUE TITLE
A problem with  the generation of the npz file.

### ISSUE THREAD

**Issue by RFalcon-Mick** [liupei101/PseMix#4]
Hello ！

I couldn’t find a method to generate npz files in the project, and I tried to create an npz file myself but failed. When using the self-generated npz file, there might be a formatting issue, preventing the model from training. I hope to get an example of an npz file to understand the structure of data storage in npz files.

Error Message：
Traceback (most recent call last):
  File "/lab/code/PseMix-main/main.py", line 65, in <module>
    multi_run_main(handler, config)
  File "/lab/code/PseMix-main/main.py", line 40, in multi_run_main
    metrics = model.exec()
  File "/lab/code/PseMix-main/model/clf_handler.py", line 126, in exec
    pids_train, pids_val, pids_test = read_datasplit_npz(path_split)
  File "/lab/code/PseMix-main/utils/io.py", line 68, in read_datasplit_npz
    pids_train = [str(s) for s in data_npz['train_patients']]
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 263, in __getitem__
    raise KeyError(f"{key} is not a file in the archive")
KeyError: 'train_patients is not a file in the archive'

May your research go smoothly.

**Comment by liupei101** [comment]
Thanks for your interest.

A valid `.npz` file could be generated using the following pseudo-code:

```python
import numpy as np

PATH_TO_SAVE_NPZ_FILE = './data_split.npz'
pids_new_train = ['train_001', ..., 'train_100'] # each string should correspond to your training slide ID
pids_new_val = ['val_01', ..., 'val_10'] # each string should correspond to your validation slide ID
pids_new_test = ['test_01', ..., 'test_100'] # each string should correspond to your test slide ID
np.savez(
    PATH_TO_SAVE_NPZ_FILE,
    train_patients=pids_new_train,
    val_patients=pids_new_val,
    test_patients=pids_test
)
```

I will update our repo to include this function.

**Comment by liupei101** [comment]
Please refer to [./data_split](https://github.com/liupei101/PseMix/tree/main/data_split) for data split results or the [Notebook - Generate Data Split](https://github.com/liupei101/PseMix/blob/main/notebooks/generate_data_split_npz.ipynb).

Feel free to post your issues here if there are additional problems.

**Comment by RFalcon-Mick** [comment]
Expressing my gratitude for your prompt and thorough response to the issue I reported.Thank you for your patience and support.
