### ISSUE TITLE
MIL paradigm and pseudo-bags

### ISSUE THREAD

**Issue by PabloMeseguerEsbri** [liupei101/PseMix#7]
Very interesting work, congrats!

How does the pseudo-bag division process handles the MIL paradigm? I mean, it is possible that some of the pseudo-bags generated and assigned with the same ground truth that the parent bag do not have any instance from the class defining the bag label thus breaching the MIL paradigm. Despite some testing on label corruption, did you make any further analysis on this issue?

Thank you in advance

**Comment by liupei101** [comment]
Thx for your interest.

As you mentioned, dividing one bag into multiple pseudo-bags could result in an undesirable situation:  there is a pseudo-bag without any instance that can determine the label assigned to this pseudo-bag. This is an inherent issue in pseudo-bag-based methods, called label noise. MIL models could be affected by it, leading to sub-optimal performance. 

There are a few interesting works that aim to alleviate the above issue. You could refer to them if interested:
- MergeUp-augmented Semi-Weakly Supervised Learning for WSI Classification, arXiv, 2024.
- Shapley Values-enabled Progressive Pseudo Bag Augmentation for Whole Slide Image Classification, IEEE TMI, 2024.
