### ISSUE TITLE
How do you evaluate during training?

### ISSUE THREAD

**Issue by weiaicunzai** [liupei101/PseMix#8]
Thank you for your work. I was wondering whether you still use PseMix during testing, or if you simply read the WSI features and pass them to the model.

If you are indeed still using PseMix during [testing](https://github.com/liupei101/PseMix/blob/3bc3cdbde880630171a600d88024a4ee881c99fe/model/clf_handler.py#L588)(although I don’t think this is the case), how do you determine the ground truth label of a given slide when you are mixing two slides together using PseMix?

**Comment by weiaicunzai** [comment]
Just make sure

**Comment by liupei101** [comment]
Hi, @weiaicunzai, thanks for your attention.

For clarification, our testing does not involve data mixing; we follow common settings in model performance evaluation.

**Comment by weiaicunzai** [comment]
> Hi, @weiaicunzai, thanks for your attention.
> 
> For clarification, our testing does not involve data mixing; we follow common settings in model performance evaluation.

Thanks!
